GameStore.WebUI/Models/CartIndexViewModel.cs
using GameStore.Domain.Entities;

namespace GameStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

GameStore.WebUI/Models/GamesListViewModel.cs
using System.Collections.Generic;
using GameStore.Domain.Entities;

namespace GameStore.WebUI.Models
{
    public class GamesListViewModel
    {
        public IEnumerable<Game> Games { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

GameStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GameStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }

        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get { return (int) Math.Ceiling((decimal) TotalItems / ItemsPerPage); }

        }

    }


}

GameStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using GameStore.Domain.Entities;
using GameStore.Domain.Abstract;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IGameRepository repository;
        public CartController(IGameRepository repo)

        {
            repository = repo;
        }
        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }


        public RedirectToRouteResult AddToCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                cart.AddItem(game, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart,int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
               cart.RemoveLine(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
      
    }
}

GameStore.WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        private IGameRepository repository;
        public int pageSize = 4;
        public GameController(IGameRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = repository.Games
                    .Where(p => category == null || p.Category== category)
                    .OrderBy(game => game.GameId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = repository.Games.Count(p => category == null || p.Category == category)
                },
                CurrentCategory = category
            };
            return View(model);
        }
        
    }

    
}

GameStore.WebUI/Views/Cart/Index.cshtml
@model GameStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "GameStore: ваша корзина";
}
<style>
    #cartTable td { vertical-align: middle;}
</style>

<h2>Ваша корзина</h2>
<table id="cartTable" class="table">
    <thead>
    <tr>
        <th>Кол-во</th>
        <th>Игра</th>
        <th class="text-right">Цена</th>
        <th class="text-right">Общая цена</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var line in Model.Cart.Lines)
    {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Game.Name</td>
            <td class="text-right">@line.Game.Price.ToString("# грн")</td>
            <td class="text-right">
                @((line.Quantity * line.Game.Price).ToString("# грн"))
            </td>
            <td>
            @using (Html.BeginForm("RemoveFromCart", "Cart"))
            {
                @Html.Hidden("GameId",line.Game.GameId)
                @Html.HiddenFor(x => x.ReturnUrl)
                <input class ="btn btn-sm btn-warning" type="submit" value="Удалить"/>
            }
                </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3" class="text-right">Итого:</td>
        <td class="text-right">
            @Model.Cart.ComputeTotalValue().ToString("# грн")
        </td>
    </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
</div>

GameStore.WebUI/Views/Cart/Summary.cshtml
@model GameStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Заказать", "Index", "Cart",
        new { returnUrl = Request.Url.PathAndQuery },
        new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text ml-auto">
    <b>Ваша корзина:</b>
    @Model.Lines.Sum(x => x.Quantity) игр,
    @Model.ComputeTotalValue().ToString("# руб")
</div>

GameStore.WebUI/Views/Game/List.cshtml
@model GamesListViewModel
@using GameStore.WebUI.Models
@using GameStore.WebUI.HtmlHelpers

@{
    ViewBag.Title = "Список ігор";
}
@foreach (var p in @Model.Games)
{
    <div class="card mb-3 bg-light p-3">
        <h3>
            <strong>@p.Name</strong>
            <span class="badge badge-primary float-right">@p.Price.ToString("# грн")</span>
        </h3>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="float-right">
                @Html.Hidden("GameId",p.GameId,new {@GameId = p.GameId})
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Добавить в корзину" />
            </div>
        }
        <span class="lead">@p.Description</span>
    </div>
}


<div class="btn-group float-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x,category = Model.CurrentCategory }))

    </div>

GameStore.WebUI/Views/Nav/Menu.cshtml
@model  IEnumerable<string>
@Html.ActionLink("Домой", "List", "Game", null, new { @class = "btn btn-block btn-lg border" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Game",
        action = "List",
        category = link,
        page = 1
    }, new
    {
        @class = "btn btn-block btn-lg border"
    + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
    })

}

GameStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    
    <title>@ViewBag.Title</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark mb-5">
    <a class="navbar-brand" href="#">GameStore - Магазин компьютерных игор </a>
    
    <div class="navbar-text " style="right: 130px !important;
                                      position: absolute;">
        <b>Ваша корзина:</b>
        3 игр,
        5297 руб
    </div>
    
    <a class="btn btn-secondary navbar-btn float-right" href="/Cart/Index?returnUrl=%2F">Заказать</a>
   
    
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
        </ul>
        <span class="navbar-text">
            @Html.Action("Summary", "Cart")
        </span>
    </div>
    
</nav>
<div class="row ">
    <div id="categories" class="col-3">
        @Html.Action("Menu","Nav")
    </div>
    <div class="col-8">
        @RenderBody()
    </div>
</div>
</body>
</html>